/**
 * Orden oficial de artistas (marquesina y listados).
 * Una sola fuente para desktop y móvil.
 */
export const ARTISTS_IN_ORDER = [
  "Omar Montes",
  "Chino & Nacho",
  "Lérica",
  "Juan Magán",
  "Álex Ubago",
  "Carlos Baute",
  "Ana Mena",
  "Micro TDH",
  "Zion & Lennox",
  "Ludmilla",
  "Don Patricio",
  "Coti",
  "Ruslana",
  "Adexe y Nau",
  "Marlena",
  "Xuso Jones",
  "Marta Sánchez",
  "Antonio José",
  "Abril",
  "Mar Lucas",
  "Danny Romero",
  "DVICIO",
  "Cruz Cafuné",
  "Ruggero",
  "María Pelae",
  "Blas Cantó",
  "Gloria Trevi",
  "Bombai",
  "Dj Nano",
  "Lu Decker",
  "Kalenn",
  "Polo Nandez",
  "Nyno Vargas",
  "Oscar El Ruso",
  "María Luna",
  "Sweet California",
  "Guzmen",
  "Kapla y Miky",
  "Lennis Rodriguez",
  "Jowell & Randy",
  "Soraya",
  "Tatiana de la Luz",
  "Miki Núñez",
  "Fabbio",
  "Jose Otero",
  "Kamilo",
  "Maytane",
  "Nerea Rodriguez",
  "Nohemy",
  "Almacor",
  "Daniela Blasco",
] as const;
