// Lista de videos - compartida para VideoWall y preload hints
export const videoFiles = [
  "Adexe y Nau - La Manera.mov",
  "Kalenn - Ya no hay canción.mov",
  "Blas Cantó - Él no soy yo.mov",
  "Carlos Baute - La Mitad.mov",
  "Carlos Baute - Y te pido perdón.mov",
  "Polo Nandez - Tú confía.mov",
  "Danny Romero - Abismo.mov",
  "Danny Romero - De Tranquilote.mov",
  "Gloria Trevi - Medusa.mov",
  "Danny Romero - Tocao.mov",
  "Dj Nano - El Nido.mov",
  "Don Patricio - En otra historia.mov",
  "Carlos Baute Ana Mena - No es para tanto.mov",
  "Guzmen - Señales.mov",
  "Jose Otero - Inviernos en Marte.mov",
  "Carlos Baute.- Muy Loco.mov",
  "Kamilo - Kids in love.mov",
  "Lu Decker - De otro color.mov",
  "Mar Lucas - Lo dejo todo.mov",
  "Maria Luna - Cabrón.mov",
  "Maytane - Miénteme.mov",
  "Miki Nuñez - Entre un millon.mov",
  "Nerea Rodriguez - Señales.mov",
  "Omar Montes - Señales.mov",
  "Bombai - Verano del 19.mov",
  "Ruslana - Lokademas.mov",
  "Sweet California - Guay.mov",
  "Sweet California - Loca.mov",
  "Xuso Jones - Mil pasos.mov",
  "Xuso Jones - Pelis de amor.mov",
];
